# Use an official Python runtime as a parent image
FROM python:3.8-slim

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED 1

# Set the working directory
WORKDIR /app

# Copy the current directory contents into the container at /app/service1
COPY . /app

# Install any needed packages specified in requirements.txt and collect static
RUN pip install --no-cache-dir -r /app/requirements.txt
RUN python manage.py collectstatic --noinput